### ISSUE TITLE
interactive shell problem - gibberish characters, backspace not working

### ISSUE THREAD

**Issue by githubuser181226** [mithrandie/csvq#83]
version 1.17.10, windows 7 sp1 x64

Hi. Thanks for the effors. The project seems to answer some of my needs, but I'm having serious issues with the shell. When typing it displays weird strings at the end of the line ie.` ←[J←[2KJ←[2K`
The backspace doesn't work properly leaving even more `←` symbols at the end of the line, left-right arrow keys are broken too making the shell completely unusable.
Attatched a screenshot. Ignore syntax error (I just typed a word and pressed enter).
Could this be Windows 7 command line related?
Regards,
![sshot-2022-10-02-10-14-59](https://user-images.githubusercontent.com/46164484/193444761-2744f77c-5d4a-4564-8a57-5fabe8236ea9.png)
Edit1. Tried running csvq.exe in cmder and the issue is gone. I think this is in deed cmd.exe related.

**Comment by mithrandie** [comment]
Windows 7 support ended more than two years ago and I no longer have any windows 7 environments, so I cannot check its behavior.

If this problem is dependent on Windows 7, I will not take action because the OS is no longer supported by the developer, but I will investigate if the same problem occurs on Windows 10 or later.

If anyone can replicate the same problem on Windows 10 or later, please report the environment and its steps.

**Comment by ondohotola** [comment]
have you rebooted?

el


--
Dr. Eberhard W. Lisse \ / Obstetrician & Gynaecologist
***@***.*** / * | Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht \ / If this email is signed with GPG/PGP
10007, Namibia ;____/ Sect 20 of Act No. 4 of 2019 may apply
